# Generated by Django 2.2 on 2019-07-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Desktop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Item ready to be Purchace'), ('Sold', 'Sold'), ('Restore', 'Item restore in few days')], default='Sold', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Item ready to be Purchace'), ('Sold', 'Sold'), ('Restore', 'Item restore in few days')], default='Sold', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('Available', 'Item ready to be Purchace'), ('Sold', 'Sold'), ('Restore', 'Item restore in few days')], default='Sold', max_length=10)),
                ('issues', models.CharField(default='No Issues', max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
